services:
  sso:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      CONFIG_PATH: /app/config/config_prod.yaml
    ports:
      - "55055:55055"
    volumes:
      - ./config:/app/config:rw
      - ./storage:/app/storage:rw
      - ./migrations:/app/migrations:rw